server:
  port: 8081
environment: prd
spring:
  data:
    #elasticsearch
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 129.204.178.49:9300
      repositories:
        enabled: true
  thymeleaf:
    cache: false
  #redis相关
  redis:
    timeout: 2000
    host: 129.204.178.49
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: syc-core-consumer

  #邮箱相关
  mail:
    host: smtp.qq.com
    username: 1481232419@qq.com
    password: nlpitwsjckzjicfc       #授权码
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: UTF-8

  #消息队列相关
  rabbitmq:
    username: guest
    password: guest
    addresses: 129.204.178.49
    listener:
      simple:
        retry:
          max-attempts: 5 #五次之后丢掉消息
          enabled: true
#feign相关
feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000
  hystrix:
    enabled: false
#ribbon相关
ribbon:
  eureka:
    enabled: true  #不然找不到微服务
  eager-load:
    enabled: true  #开启Ribbon的饥饿加载模式,防止read time out
    clients: syc-core-provider  #指定需要饥饿加载的服务名
#eureka相关
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka #找eureka地址，
    healthcheck:
      enabled: true
  instance:
    instance-id: syc-core-consumer-${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30  #续约更新时间间隔
    lease-expiration-duration-in-seconds: 90 #表示eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该instance

info:
  app.name: syc-core-consumer
  build.artifactId: @project.artifactId@
  build.version: @project.version@
  build.port: ${server.port}
  build.ip: ${self.remote-server}

logging:
  level:
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: WARN #不输出心跳检测日志
    org.springframework.boot.autoconfigure: ERROR  #去掉不用的启动日志
    com.netflix.discovery.DiscoveryClient: WARN  #不输出服务发现日志
    com.syc.blog.mapper: DEBUG
  config: classpath:config/logback-spring.xml
  path: $[log.path]  #logback-spring.xml 取值
